import os
import json
import shutil
import subprocess
from pathlib import Path
import sys
from eth_keys import keys
from eth_utils import to_checksum_address

NUM_VALIDATORS = 4  # 검증 노드 수
NUM_TOTAL_NODES = NUM_VALIDATORS + 1 # 전체 노드 수 (검증 노드 + RPC 노드)
CHAIN_ID = 20250707
DOCKER_NETWORK = "krdpp-network"
PROJECT_DIR = Path(__file__).parent.resolve()
CONFIG_DIR = PROJECT_DIR / "config"
DOCKER_COMPOSE_FILE = PROJECT_DIR / "docker-compose.yml"
INITIAL_BALANCE = "0x1000000000000000000000"  # 1,000,000 ETH in wei (16진수 문자열)

def create_initial_config(consensus, block_period_seconds=2):
    """ Besu CLI용 초기 config 생성 (키 생성 없이) """
    config_path = PROJECT_DIR / "config.json"
    config_data = {
        "genesis": {
            "config": {
                "chainId": CHAIN_ID,
                "berlinBlock": 0,
                "minGasPrice": "0x0",
                consensus: {
                    "blockperiodseconds": block_period_seconds,
                    "epochlength": 30000,
                    "requesttimeoutseconds": 4
                }
            },
            "nonce": "0x0",
            "timestamp": "0x67691858",
            "gasLimit": "0x1fffffffffffff",
            "difficulty": "0x1",
            "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
            "coinbase": "0x0000000000000000000000000000000000000000",
            "alloc": {},  # Besu CLI가 생성한 키로 나중에 업데이트
            "extraData": "0x"
        },
        "blockchain": {
            "nodes": {
                "generate": True,
                "count": NUM_VALIDATORS # 검증 노드 수만큼 키 생성
            }
        },
        "nodes": []  # Besu가 자동 생성
    }

    # config JSON 저장
    with open(config_path, "w") as f:
        json.dump(config_data, f, indent=2)

    print(f"[INFO] config.json 생성 완료 (블록 생성 주기: {block_period_seconds}초)")
    return config_path

def run_besu_operator(config_path):
    if CONFIG_DIR.exists():
        shutil.rmtree(CONFIG_DIR)
    CONFIG_DIR.mkdir()
    cmd = [
        "besu",
        "operator",
        "generate-blockchain-config",
        "--config-file", str(config_path),
        "--to", str(CONFIG_DIR)
    ]
    print(f"Running: {' '.join(cmd)}")
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print("[ERROR] Besu CLI 실행 실패:")
        print(result.stderr)
        sys.exit(1)
    print("[INFO] Besu CLI 성공")

def read_besu_keys_and_create_validators():
    """ Besu CLI가 생성한 키를 읽어서 validators.json 생성 """
    keys_dir = CONFIG_DIR / "keys"
    if not keys_dir.exists():
        print("[ERROR] config/keys 디렉토리가 없습니다.")
        sys.exit(1)
    
    # 생성된 키 폴더는 검증 노드 수만큼이어야 함
    key_folders = sorted([d for d in keys_dir.iterdir() if d.is_dir()])
    if len(key_folders) != NUM_VALIDATORS:
        print(f"[ERROR] keys 폴더 내 노드 수({len(key_folders)})가 NUM_VALIDATORS({NUM_VALIDATORS})와 다릅니다.")
        sys.exit(1)
    
    validators = []
    for key_dir in key_folders:
        priv_file = key_dir / "key.priv"
        if not priv_file.exists():
            print(f"[ERROR] {priv_file} 파일이 없습니다.")
            sys.exit(1)
        
        with open(priv_file, "r") as f:
            priv_hex = f.read().strip()
        if priv_hex.startswith("0x") or priv_hex.startswith("0X"):
            priv_hex = priv_hex[2:]
        
        # 주소 계산
        priv_key = keys.PrivateKey(bytes.fromhex(priv_hex))
        address = to_checksum_address(priv_key.public_key.to_address())
        
        validators.append({
            "address": address,
            "private_key": "0x" + priv_hex,
            "comment": "Generated by Besu CLI - If you have any questions, please contact jinhyeok"
        })
    
    # validators.json 저장
    with open("validators.json", "w") as f:
        json.dump(validators, f, indent=2)
    
    print(f"[INFO] Besu CLI 키 기반 validators.json 생성 완료 ({len(validators)}개 validator)")
    return validators

def update_genesis_with_alloc(validators, consensus):
    """ genesis.json에 validator들의 초기 잔액 정보 추가 """
    genesis_file = CONFIG_DIR / "genesis.json"
    if not genesis_file.exists():
        print("[ERROR] genesis.json 파일이 없습니다.")
        sys.exit(1)
    
    with open(genesis_file, "r") as f:
        genesis_data = json.load(f)
    
    # alloc 섹션에 validator들의 초기 잔액 추가
    if "alloc" not in genesis_data:
        genesis_data["alloc"] = {}
    
    for validator in validators:
        genesis_data["alloc"][validator["address"]] = {
            "balance": INITIAL_BALANCE
        }
    
    # 업데이트된 genesis.json 저장
    with open(genesis_file, "w") as f:
        json.dump(genesis_data, f, indent=2)
    
    print(f"[INFO] genesis.json에 {len(validators)}개 validator의 초기 잔액 정보 추가 완료")

def generate_address_and_enode_files():
    # 검증 노드에 대한 키 파일 처리
    key_folders = sorted([d for d in (CONFIG_DIR / "keys").iterdir() if d.is_dir()])
    if len(key_folders) != NUM_VALIDATORS:
        print(f"[ERROR] keys 폴더 내 노드 수({len(key_folders)})가 NUM_VALIDATORS({NUM_VALIDATORS})와 다릅니다.")
        sys.exit(1)

    for i, key_dir in enumerate(key_folders, start=1):
        priv_file = key_dir / "key.priv"
        pub_file = key_dir / "key.pub"
        if not priv_file.exists() or not pub_file.exists():
            print(f"[ERROR] {priv_file} 또는 {pub_file} 파일이 없습니다.")
            sys.exit(1)

        with open(priv_file, "r") as f:
            priv_hex = f.read().strip()
        if priv_hex.startswith("0x") or priv_hex.startswith("0X"):
            priv_hex = priv_hex[2:]

        with open(pub_file, "r") as f:
            pub_hex = f.read().strip()
        if pub_hex.startswith("0x") or pub_hex.startswith("0X"):
            pub_hex = pub_hex[2:]

        priv_key = keys.PrivateKey(bytes.fromhex(priv_hex))
        pub_key = keys.PublicKey(bytes.fromhex(pub_hex))

        address = to_checksum_address(pub_key.to_address())
        with open(key_dir / "address", "w") as f:
            f.write(address)

        pubkey_hex = pub_key.to_hex()[2:]  # '0x' 제거
        # Docker 네트워크에서 고정 IP 사용 (192.168.100.10 + i)
        node_ip = f"192.168.100.{10 + i}"
        enode = f"enode://{pubkey_hex}@{node_ip}:30303"
        with open(key_dir / "enode", "w") as f:
            f.write(enode)

        print(f"[INFO] {key_dir.name} (node{i}) address 및 enode 파일 생성 완료")

    # RPC 노드용 data 디렉토리를 만들어두는 것으로 충분.
    # RPC 노드도 Besu 컨테이너가 시작될 때 `--data-path`가 필요하므로,
    # 비록 키는 없더라도 빈 디렉토리는 필요하다.
    rpc_node_dir = PROJECT_DIR / f"node{NUM_TOTAL_NODES}" / "data"
    rpc_node_dir.mkdir(parents=True, exist_ok=True)
    print(f"[INFO] RPC 노드용 data 폴더 생성 완료: {rpc_node_dir}")

def distribute_keys():
    # 검증 노드에 대한 키 분배
    key_folders = sorted([d for d in (CONFIG_DIR / "keys").iterdir() if d.is_dir()])
    if len(key_folders) != NUM_VALIDATORS:
        print(f"[ERROR] keys 폴더 내 노드 수({len(key_folders)})가 NUM_VALIDATORS({NUM_VALIDATORS})와 다릅니다.")
        sys.exit(1)

    for i, key_dir in enumerate(key_folders, start=1):
        dest_dir = PROJECT_DIR / f"node{i}" / "data"
        dest_dir.mkdir(parents=True, exist_ok=True)

        # key.priv → key로 복사 (Besu가 /data/key 파일을 찾음)
        priv_file = key_dir / "key.priv"
        if priv_file.exists():
            shutil.copy(priv_file, dest_dir / "key")
        else:
            print(f"[ERROR] {priv_file} 파일이 없습니다.")
            sys.exit(1)
        
        # 나머지 파일들 복사
        for file_name in ["key.pub", "address", "enode"]:
            src_file = key_dir / file_name
            if src_file.exists():
                shutil.copy(src_file, dest_dir / file_name)
            else:
                print(f"[WARN] {src_file} 파일이 없습니다. 건너뜁니다.")
        
        print(f"[INFO] {key_dir.name} → node{i}/data/로 키 파일 복사 완료 (key.priv → key)")

    # RPC 노드용 데이터 디렉토리는 이미 generate_address_and_enode_files 에서 생성됨
    # 하지만 distribute_keys 함수는 검증 노드 키를 분배하는 주 목적을 가지므로,
    # 여기서는 RPC 노드에 키를 복사할 필요가 없음.
    # 만약 RPC 노드도 특정 키 파일이 필요하다면 여기에 추가 로직을 넣어야 합니다.


def collect_enodes():
    enodes = []
    for i in range(1, NUM_VALIDATORS + 1): # 검증 노드의 enode만 수집
        enode_path = PROJECT_DIR / f"node{i}" / "data" / "enode"
        if not enode_path.exists():
            print(f"[ERROR] {enode_path} 파일이 없습니다.")
            sys.exit(1)
        with open(enode_path, "r") as f:
            enode = f.read().strip()
            enodes.append(enode)
    return enodes

def create_env_file():
    """각 노드의 private key와 public key를 .env 파일로 생성"""
    env_content = "# Besu Network Node Keys\n"
    env_content += "# Generated automatically - Do not edit manually\n\n"
    
    # validators.json에서 키 정보 읽기
    validators_file = PROJECT_DIR / "validators.json"
    if not validators_file.exists():
        print("[WARN] validators.json 파일이 없어서 .env 파일을 생성할 수 없습니다.")
        return
    
    with open(validators_file, "r") as f:
        validators = json.load(f)
    
    # 각 검증 노드의 키 정보 추가
    for i, validator in enumerate(validators, start=1):
        private_key = validator["private_key"]
        address = validator["address"]
        
        # public key 파일에서 읽기
        pub_key_path = PROJECT_DIR / f"node{i}" / "data" / "key.pub"
        if pub_key_path.exists():
            with open(pub_key_path, "r") as f:
                public_key = f.read().strip()
                if not public_key.startswith("0x"):
                    public_key = "0x" + public_key
        else:
            public_key = "# Public key file not found"
        
        env_content += f"# Node{i} (Validator)\n"
        env_content += f"NODE{i}_PRIVATE_KEY={private_key}\n"
        env_content += f"NODE{i}_PUBLIC_KEY={public_key}\n"
        env_content += f"NODE{i}_ADDRESS={address}\n\n"
    
    # RPC 노드는 키가 없으므로 주석으로 표시
    env_content += f"# Node{NUM_TOTAL_NODES} (RPC Only - No keys)\n"
    env_content += f"# NODE{NUM_TOTAL_NODES}_PRIVATE_KEY=N/A\n"
    env_content += f"# NODE{NUM_TOTAL_NODES}_PUBLIC_KEY=N/A\n"
    env_content += f"# NODE{NUM_TOTAL_NODES}_ADDRESS=N/A\n\n"
    
    # 네트워크 정보 추가
    env_content += "# Network Information\n"
    env_content += f"CHAIN_ID={CHAIN_ID}\n"
    env_content += f"NUM_VALIDATORS={NUM_VALIDATORS}\n"
    env_content += f"NUM_TOTAL_NODES={NUM_TOTAL_NODES}\n"
    
    # .env 파일 저장
    env_file = PROJECT_DIR / ".env"
    with open(env_file, "w") as f:
        f.write(env_content)
    
    print(f"[INFO] .env 파일 생성 완료: {env_file}")
    print(f"[INFO] {len(validators)}개 검증 노드의 키 정보가 포함되었습니다.")

def create_docker_compose(enodes, consensus, validator_profile="enterprise", rpc_profile="enterprise"):
    # 첫 번째 노드 enode만 부트노드로 사용
    first_bootnode = enodes[0]

    content = f"""version: "3.8"
services:
"""
    # 검증 노드 서비스 정의 (node1 ~ node4)
    for i in range(1, NUM_VALIDATORS + 1):
        http_port = 8544 + i
        p2p_port = 30302 + i

        bootnodes_option = ""
        if i != 1:
            bootnodes_option = f"--bootnodes={first_bootnode}"

        node_ip = f"192.168.100.{10 + i}"
        
        # command를 리스트 형태로 구성
        command_args = [
            "--data-path=/data",
            "--genesis-file=/config/genesis.json",
            f"--profile={validator_profile}",
            "--rpc-http-enabled",
            "--rpc-http-port=8545",
            "--rpc-http-api=ETH,NET,WEB3,DEBUG,ADMIN,TXPOOL,TRACE,PLUGINS,IBFT",
            "--rpc-http-cors-origins=*",
            "--rpc-http-host=0.0.0.0",
            "--rpc-http-max-active-connections=16384",
            "--rpc-http-max-batch-size=-1",
            "--host-allowlist=*",
            "--p2p-port=30303",
        ]
        if bootnodes_option: # 첫 번째 노드가 아닌 경우에만 추가
            command_args.append(bootnodes_option)
        command_args.extend([
            "--rpc-ws-enabled",
            "--rpc-ws-port=8546",
            "--rpc-ws-api=ETH,NET,WEB3,DEBUG,ADMIN,TXPOOL,TRACE,PLUGINS,IBFT",
            "--rpc-ws-host=0.0.0.0",
            "--rpc-ws-max-active-connections=16384",
            "--tx-pool-price-bump=0",
            "--fast-sync-min-peers=1",
            "--min-gas-price=0",
            "--data-storage-format=BONSAI",
            "--bonsai-maximum-back-layers-to-load=512"
        ])

        # YAML 리스트 형태로 변환하여 content에 추가
        command_yaml_list = "\n".join([f'      - "{arg}"' for arg in command_args])

        content += f"""
  node{i}:
    image: hyperledger/besu:latest
    container_name: besu-node{i}
    ports:
      - "{http_port}:8545"
      - "{p2p_port}:30303"
    volumes:
      - ./node{i}/data:/data
      - ./config/genesis-{consensus}.json:/config/genesis.json
    networks:
      besu-network:
        ipv4_address: {node_ip}
    command:
{command_yaml_list}
"""

    # RPC 전용 노드 서비스 정의 (node5)
    rpc_node_index = NUM_VALIDATORS + 1 # 5번째 노드
    rpc_http_port = 8550 # 검증 노드와 겹치지 않게 포트 설정
    rpc_ws_port = 8551
    rpc_p2p_port = 30307 # RPC 노드도 P2P 통신은 해야 함
    rpc_node_ip = f"192.168.100.{10 + rpc_node_index}"

    # RPC 노드의 command를 리스트 형태로 구성
    rpc_command_args = [
        "--data-path=/data",
        "--genesis-file=/config/genesis.json",
        f"--profile={rpc_profile}",
        "--rpc-http-enabled",
        "--rpc-http-port=8545",
        "--rpc-http-api=ETH,NET,WEB3,DEBUG,ADMIN,TXPOOL,TRACE,PLUGINS,IBFT",
        "--rpc-http-cors-origins=*",
        "--rpc-http-host=0.0.0.0",
        "--rpc-http-max-active-connections=32768",  # RPC 노드는 더 많은 연결 허용
        "--rpc-http-max-batch-size=-1",
        "--host-allowlist=*",
        "--p2p-port=30303",
        f"--bootnodes={first_bootnode}", # RPC 노드도 부트노드를 통해 연결
        "--rpc-ws-enabled",
        "--rpc-ws-port=8546",
        "--rpc-ws-api=ETH,NET,WEB3,DEBUG,ADMIN,TXPOOL,TRACE,PLUGINS,IBFT",
        "--rpc-ws-host=0.0.0.0",
        "--rpc-ws-max-active-connections=32768",
        "--tx-pool-price-bump=0",
        "--fast-sync-min-peers=1",
        "--min-gas-price=0",
        "--miner-enabled=false", # 채굴(블록 생성) 비활성화
        # Bonsai Tries 최적화
        "--data-storage-format=BONSAI",
        "--bonsai-maximum-back-layers-to-load=1024",
        # P2P 최적화 (RPC는 더 많은 연결)
        "--max-peers=100"
    ]
    rpc_command_yaml_list = "\n".join([f'      - "{arg}"' for arg in rpc_command_args])

    content += f"""
  node{rpc_node_index}:
    image: hyperledger/besu:latest
    container_name: besu-node{rpc_node_index}-rpc
    ports:
      - "{rpc_http_port}:8545" # 외부 포트 변경
      - "{rpc_ws_port}:8546"  # 외부 포트 변경
      - "{rpc_p2p_port}:30303" # P2P 포트
    volumes:
      - ./node{rpc_node_index}/data:/data
      - ./config/genesis-{consensus}.json:/config/genesis.json
    networks:
      besu-network:
        ipv4_address: {rpc_node_ip}
    command:
{rpc_command_yaml_list}
"""

    # Docker 네트워크 설정 추가
    content += """
networks:
  besu-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
"""

    with open(DOCKER_COMPOSE_FILE, "w") as f:
        f.write(content)

def soft_reset():
    """키는 유지하고 profile만 변경하여 docker-compose.yml을 재생성"""
    print("\n=== Besu 소프트 리셋 (Profile 변경) ===")
    
    # 기존 키와 설정이 있는지 확인
    if not (CONFIG_DIR / "genesis-ibft2.json").exists() and not (CONFIG_DIR / "genesis-qbft.json").exists():
        print("[ERROR] 기존 genesis 파일이 없습니다. 먼저 전체 설정을 생성하세요.")
        return
    
    # consensus 타입 감지
    if (CONFIG_DIR / "genesis-ibft2.json").exists():
        consensus = "ibft2"
    else:
        consensus = "qbft"
    
    print(f"감지된 컨센서스: {consensus}")
    
    # Profile 선택
    print("\n검증 노드 Profile:")
    print("1. enterprise")
    print("2. performance")
    while True:
        choice = input("검증 노드 Profile을 선택하세요 (1 또는 2): ").strip()
        if choice == "1" or choice == "":
            validator_profile = "enterprise"
            break
        elif choice == "2":
            validator_profile = "performance"
            break
        else:
            print("잘못된 입력입니다. 1 또는 2를 입력하세요.")
    
    print("\nRPC 노드 Profile:")
    print("1. enterprise")
    print("2. performance_rpc") 
    print("3. performance")
    while True:
        choice = input("RPC 노드 Profile을 선택하세요 (1, 2 또는 3): ").strip()
        if choice == "1" or choice == "":
            rpc_profile = "enterprise"
            break
        elif choice == "2":
            rpc_profile = "performance_rpc"
            break
        elif choice == "3":
            rpc_profile = "performance"
            break
        else:
            print("잘못된 입력입니다. 1, 2 또는 3을 입력하세요.")
    
    # 기존 enode 수집
    enodes = collect_enodes()
    
    # docker-compose.yml 재생성
    create_docker_compose(enodes, consensus, validator_profile, rpc_profile)
    
    print(f"\n=== 소프트 리셋 완료! ===")
    print(f"검증 노드 Profile: {validator_profile}")
    print(f"RPC 노드 Profile: {rpc_profile}")
    print("docker-compose.yml이 새로운 profile로 업데이트되었습니다.")
    print("▶ docker-compose down && docker-compose up -d 로 재시작하세요.")

def get_block_period_settings():
    """블록 생성 주기 설정을 가져옵니다"""
    print("\n블록 생성 속도 설정:")
    print("1. TPS 테스트용 (0.5초 - 매우 빠름)")
    print("2. 일반용 (2초 - 기본값)")
    print("3. 안정성 중심 (5초 - 느리지만 안정적)")
    print("4. 커스텀 입력")
    
    while True:
        choice = input("블록 생성 속도를 선택하세요 (1-4): ").strip()
        if choice == "1":
            return 0.5, "TPS 테스트용 (0.5초)"
        elif choice == "2" or choice == "":
            return 2, "일반용 (2초)"
        elif choice == "3":
            return 5, "안정성 중심 (5초)"
        elif choice == "4":
            while True:
                try:
                    custom_seconds = float(input("블록 생성 주기를 초 단위로 입력하세요 (0.1-30): ").strip())
                    if 0.1 <= custom_seconds <= 30:
                        return custom_seconds, f"커스텀 ({custom_seconds}초)"
                    else:
                        print("0.1초부터 30초 사이의 값을 입력하세요.")
                except ValueError:
                    print("올바른 숫자를 입력하세요.")
        else:
            print("잘못된 입력입니다. 1-4 중 선택하세요.")

def main():
    print("\n=== Besu 네트워크 자동 생성기 ===")
    print("1. 전체 설정 생성 (새로운 키 생성)")
    print("2. 소프트 리셋 (키 유지, Profile만 변경)")
    
    while True:
        mode = input("모드를 선택하세요 (1 또는 2): ").strip()
        if mode == "1" or mode == "":
            break
        elif mode == "2":
            soft_reset()
            return
        else:
            print("잘못된 입력입니다. 1 또는 2를 입력하세요.")
    
    print(f"\n검증 노드 수: {NUM_VALIDATORS}개, RPC 전용 노드 수: 1개")
    print("1. IBFT2 (기본)")
    print("2. QBFT")
    while True:
        choice = input("컨센서스 타입을 선택하세요 (1 또는 2): ").strip()
        if choice == "1" or choice == "":
            consensus = "ibft2"
            break
        elif choice == "2":
            consensus = "qbft"
            break
        else:
            print("잘못된 입력입니다. 1 또는 2를 입력하세요.")
    
    # 블록 생성 속도 설정
    block_period_seconds, block_setting_desc = get_block_period_settings()
    
    # Profile 선택
    print("\n검증 노드 Profile:")
    print("1. enterprise (기본)")
    print("2. performance")
    while True:
        choice = input("검증 노드 Profile을 선택하세요 (1 또는 2): ").strip()
        if choice == "1" or choice == "":
            validator_profile = "enterprise"
            break
        elif choice == "2":
            validator_profile = "performance"
            break
        else:
            print("잘못된 입력입니다. 1 또는 2를 입력하세요.")
    
    print("\nRPC 노드 Profile:")
    print("1. enterprise (기본)")
    print("2. performance_rpc") 
    print("3. performance")
    while True:
        choice = input("RPC 노드 Profile을 선택하세요 (1, 2 또는 3): ").strip()
        if choice == "1" or choice == "":
            rpc_profile = "enterprise"
            break
        elif choice == "2":
            rpc_profile = "performance_rpc"
            break
        elif choice == "3":
            rpc_profile = "performance"
            break
        else:
            print("잘못된 입력입니다. 1, 2 또는 3을 입력하세요.")

    # 1. Besu CLI용 초기 config 생성 (키 없이)
    # config.json은 검증 노드 수만큼의 키를 생성하도록 지시
    config_path = create_initial_config(consensus, block_period_seconds)
    
    # 2. Besu CLI 실행해서 키와 genesis 생성
    run_besu_operator(config_path)
    
    # 3. Besu CLI가 생성한 키를 읽어서 validators.json 생성
    validators = read_besu_keys_and_create_validators()
    
    # 4. genesis.json에 validator들의 초기 잔액 정보 추가
    update_genesis_with_alloc(validators, consensus)
    
    # 5. 키 관련 파일들 생성 및 배포 (검증 노드용)
    generate_address_and_enode_files()
    distribute_keys() # 검증 노드 키 분배 및 RPC 노드용 data 폴더 생성
    enodes = collect_enodes() # 검증 노드들의 enode만 수집

    # genesis.json 이름 변경
    genesis_file = CONFIG_DIR / "genesis.json"
    genesis_new = CONFIG_DIR / f"genesis-{consensus}.json"
    if genesis_file.exists():
        genesis_file.rename(genesis_new)
    else:
        print("[ERROR] genesis.json 파일이 없습니다.")
        sys.exit(1)

    # docker-compose.yml 파일 생성 (검증 노드 + RPC 노드 포함)
    create_docker_compose(enodes, consensus, validator_profile, rpc_profile)
    
    # .env 파일 생성
    create_env_file()

    print("\n=== 생성 완료! ===")
    print(f"- config 디렉토리: {CONFIG_DIR}")
    print(f"- genesis 파일: {genesis_new}")
    print(f"- docker-compose 파일: {DOCKER_COMPOSE_FILE}")
    print(f"- .env 파일: {PROJECT_DIR}/.env")
    print(f"- 블록 생성 설정: {block_setting_desc}")
    print(f"- 검증 노드 Profile: {validator_profile}")
    print(f"- RPC 노드 Profile: {rpc_profile}")
    for i in range(1, NUM_VALIDATORS + 1):
        print(f"- node{i} (검증 노드) data 폴더: ./node{i}/data")
    print(f"- node{NUM_TOTAL_NODES} (RPC 전용 노드) data 폴더: ./node{NUM_TOTAL_NODES}/data")
    print(f"\n▶ docker-compose up -d 로 네트워크 실행하세요.")
    print(f"RPC 노드 HTTP 포트: {8550}, WS 포트: {8551}")
    
    # TPS 정보 추가
    theoretical_tps = 1 / block_period_seconds
    print(f"\n📊 예상 최대 TPS: ~{theoretical_tps:.1f} (블록당 1개 트랜잭션 기준)")
    if block_period_seconds <= 1:
        print("⚠️  TPS 테스트용 설정입니다. 프로덕션 환경에서는 더 긴 블록 주기를 권장합니다.")
    
    print(f"\n💡 Tip: 나중에 Profile만 변경하고 싶으면 'python setup_besu.py'로 다시 실행하고 '2. 소프트 리셋'을 선택하세요.")

if __name__ == "__main__":
    main()